ArtsukiWeb/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ArtsukiDomain.Entities;
using ArtsukiService;
using ArtsukiWeb.Models;
using RestSharp;
using RestSharp.Deserializers;

namespace ArtsukiWeb.Controllers
{
    public class ShopController : Controller
    {
        private IItemService itemService = new ItemService();
        private IOrderService orderService = new OrderService();

        private ArtsukiViewModel connectedUser;
        private IMemberService memberService = new MemberService();
        private const string BASE_URI = "http://localhost:18080/tn.esprit.twin.artsuki-web/api/";
        private static string UPLOAD_PATH = "~/Content/Upload/Shop/";

        private string token;

        public void authenticate()
        {
            var client = new RestClient(BASE_URI);
            var request = new RestRequest(Method.POST);
            client.ClearHandlers();
            client.AddHandler("application/json", new JsonDeserializer());
            request.RequestFormat = DataFormat.Json;
            request.Resource = "authentication/";
            var obj = new
            {
                email = "artsuki7@artsuki.com",
                password = "753357"

            };
            request.AddJsonBody(obj);
            client.AddDefaultHeader("accept", "*/*");
            var response = client.Execute(request);
            token = response.Content;
        }
        [Route("Token")]
        public ActionResult Token()
        {
            authenticate();
            return Content(token);
        }

        public ArtsukiViewModel getConnectedUser()
        {
            if (token == null)
            {
                authenticate();
            }

            if (connectedUser == null)
            {
                var client = new RestClient(BASE_URI);
                client.AddDefaultHeader("accept", "*/*");
                client.AddDefaultHeader("authorization", "Bearer " + token);
                var request = new RestRequest(Method.GET);
                request.Resource = "artsuki";
                var response = client.Execute<ArtsukiViewModel>(request);
                if (response.StatusCode == HttpStatusCode.Unauthorized)
                {
                    authenticate();
                    getConnectedUser();
                }
                connectedUser = response.Data;
                return connectedUser;
            }
            return connectedUser;
        }

        // GET: Shop
        public ActionResult Index()
        {
            ViewBag.UploadPath = Url.Content(UPLOAD_PATH);
            var Items = itemService.GetItems();
            return View(Items);
        }

        // GET: Shop/Details/5
        public ActionResult Details(int id)
        {
            Item itemToDisplay = itemService.Get(i => i.Id == id);
            var Owner = memberService.Get(a => a.id == itemToDisplay.ArtsukiId);
            ViewBag.UploadPath = Url.Content(UPLOAD_PATH);
            ViewBag.Connected = getConnectedUser();
            ViewBag.Owner = Owner;
            return View(itemToDisplay);
        }

        // GET: Shop/Create
        public ActionResult Create()
        { 
            return View();
        }

        // POST: Shop/Create
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase Image)
        {
                
                // TODO: Add insert logic here
                var label = Request.Form["label"];
                var description = Request.Form["description"];
                var price = Request.Form["price"];
                var imageName = Path.GetFileName(Image.FileName);
                string path = Path.Combine(Server.MapPath(UPLOAD_PATH), imageName);
                Image.SaveAs(path);
                ArtsukiViewModel connected = getConnectedUser();
                var artsukiConnected = memberService.Get(a => a.id == connected.id);
                Item item = new Item()
                {
                    Label = label,
                    Description = description,
                    ImageName = imageName,
                    Price = Double.Parse(price),
                    ArtsukiId = artsukiConnected.id
                };
                itemService.Add(item);
                itemService.Commit();
                return RedirectToAction("Index");
            
        }

        // GET: Shop/Edit/5
        public ActionResult Edit(int id)
        {
            Item itemFetchedToModify = itemService.Get(i => i.Id == id);
            return View(itemFetchedToModify);
        }

        // POST: Shop/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase photo)
        {
            try
            {
                // TODO: Add update logic here
                var label = Request.Form["label"];
                var description = Request.Form["description"];
                var price = Request.Form["price"];
                var photoName = Request.Form["imageNameReserve"];
                if (photo != null && photo.ContentLength > 0)
                {
                    // TODO: Add insert logic here
                    photoName = Path.GetFileName(photo.FileName);
                    string path = Path.Combine(Server.MapPath(UPLOAD_PATH),photoName);
                    photo.SaveAs(path);
                }
                Item itemFetchedToModify = itemService.Get(i => i.Id == id);
                itemFetchedToModify.Label = label;
                itemFetchedToModify.Description = description;
                itemFetchedToModify.ImageName = photoName;
                itemFetchedToModify.Price = Double.Parse(price);
                itemService.Update(itemFetchedToModify);
                itemService.Commit();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Shop/Delete/5
        public ActionResult Delete(int id)
        {
            Item itemFetchedToDelete = itemService.Get(i => i.Id == id);
            itemService.Delete(itemFetchedToDelete);
            itemService.Commit();
            return RedirectToAction("Index");
        }

        [Route("Item/{id}/Buy")]
        public ActionResult Buy(int id)
        {
            Item itemToBuy = itemService.Get(i => i.Id == id);
            if (itemToBuy.Order != null)
            {
                return RedirectToAction("Index");
            }
            var connectedUser = getConnectedUser();
            if (itemToBuy.ArtsukiId == connectedUser.id)
            {
                ViewBag.message = "You Can't Buy Your Own Product";
                return RedirectToAction("Index");  
            }
            else
            {
                orderService.AddOrder(connectedUser.id, id);
                return RedirectToAction("Index");
            }
        }

        [Route("Item/MyItems")]
        public ActionResult MyItems()
        {
            var connected = getConnectedUser();
            ViewBag.UploadPath = Url.Content(UPLOAD_PATH);
            var myItems = itemService.GetMany(i => i.ArtsukiId == connected.id).ToList();
            return View(myItems);
        }

        [Route("Orders/MyOrders")]
        public ActionResult MyOrders()
        {
            var connected = getConnectedUser();
            ViewBag.UploadPath = Url.Content(UPLOAD_PATH);
            var myOrders = orderService.GetMany(o => o.ArtsukiId == connected.id).ToList();
            return View(myOrders);
        }

    }
}

ArtsukiWeb/Views/Shared/_Details.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="FotoFly">
    <meta name="author" content="Frenify">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Anonymous+Pro:400,400i,700,700i|Poppins:300,400,500,600,700&amp;subset=cyrillic" rel="stylesheet">
    <!-- STYLES -->
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/mytemplate/")css/plugins.css" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/mytemplate/")css/style.css" />
    <!--[if lt IE 9]> <script type="text/javascript" src="js/modernizr.custom.js"></script> <![endif]-->
    <!-- /STYLES -->
    <!-- SCRIPTS -->
    <script type="text/javascript" src="@Url.Content("~/Content/mytemplate/")js/jquery.js"></script>
    <!--[if lt IE 10]> <script type="text/javascript" src="js/ie8.js"></script> <![endif]-->
    <script type="text/javascript" src="@Url.Content("~/Content/mytemplate/")js/plugins.js"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/mytemplate/")js/init.js"></script>
    <!-- /SCRIPTS -->
</head>
<body>
    <!-- WRAPPER ALL -->
    <div class="fotofly_fn_wrapper_all" data-totop="on">

        <!-- HEADER -->
        <header class="fotofly_fn_header">
            <div class="fotofly_fn_header_content">
                <div class="header_inner">
                    <!-- FOR HUGESIZE SCREENS -->
                    <div class="header_list">
                        <ul class="nav__hor">
                            <li><a class="fotofly_fn_animated_link" href="/Home/Index">Home</a></li>
                            <li><a class="fotofly_fn_animated_link" href="/Home/Gallery">Gallery</a></li>
                            <li><a class="fotofly_fn_animated_link" href="/Home/Portfolio">Portfolio</a></li>
                        </ul>
                        <div class="logo">
                            <a href="/Home/Index">
                                <img class="light" src="@Url.Content("~/Content/mytemplate/")img/logo.png" alt="" />
                                <img class="dark" src="@Url.Content("~/Content/mytemplate/")img/logo.png" alt="" />
                            </a>
                        </div>
                        <ul class="nav__hor">
                            <li><a class="fotofly_fn_animated_link" href="/Home/Event">Events</a></li>
                            <li><a class="fotofly_fn_animated_link" href="/Community/Index">Blog</a></li>
                            <li><a class="fotofly_fn_animated_link" href="/Home/Profil">Profil</a></li>
                        </ul>
                    </div>
                    <!-- /FOR HUGESIZE SCREENS -->
                    <!-- EXTRA BUTTONS -->
                    <div class="header_helper">
                        <ul>
                            <li class="search">
                                <a href="#"><img class="svg" src="@Url.Content("~/Content/mytemplate/")img/svg/search.svg" alt="" /></a>
                                <div class="fotofly_fn_search">
                                    <div class="in">
                                        <input type="search" placeholder="Search" />
                                        <a href="#"><img class="svg" src="@Url.Content("~/Content/mytemplate/")img/svg/search.svg" alt="" /></a>
                                    </div>
                                </div>
                            </li>
                            <li class="share">
                                <a href="#"><img class="svg" src="@Url.Content("~/Content/mytemplate/")img/svg/share.svg" alt="" /></a>
                                <ul class="hidden">
                                    <li><a href="#"><i class="xcon-facebook-1"></i></a></li>
                                    <li><a href="#"><i class="xcon-instagram"></i></a></li>
                                    <li><a href="#"><i class="xcon-pinterest-1"></i></a></li>
                                    <li><a href="#"><i class="xcon-twitter-1"></i></a></li>
                                    <li><a href="#"><i class="xcon-gplus-1"></i></a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </header>
        <!-- /HEADER -->
        <div>
            @RenderBody()
        </div>
        <!-- PAGINATION -->
        <div class="fotofly_fn_pagination">
            <div class="pagination">
                <ul>
                    <li><a class="active" href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li class="next"><a href="#">Next</a></li>
                </ul>
            </div>
        </div>
        <!-- /PAGINATION -->
        <!-- FOOTER -->
        <footer class="fotofly_fn_footer">
            <div class="copyright">
                <span>Copyright 2017. Designed by <a href="#">Frenify</a></span>
            </div>
        </footer>
        <!-- /FOOTER -->
    </div>
</body>
</html>

ArtsukiWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom de l'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("À propos de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ArtsukiWeb/Views/Shared/_Loading.cshtml
<div class="sk-cube-grid loader">
    <div class="sk-cube sk-cube1"></div>
    <div class="sk-cube sk-cube2"></div>
    <div class="sk-cube sk-cube3"></div>
    <div class="sk-cube sk-cube4"></div>
    <div class="sk-cube sk-cube5"></div>
    <div class="sk-cube sk-cube6"></div>
    <div class="sk-cube sk-cube7"></div>
    <div class="sk-cube sk-cube8"></div>
    <div class="sk-cube sk-cube9"></div>
</div>

ArtsukiWeb/Views/Shared/_Menu.cshtml
<header class="fotofly_fn_header">
    <div class="fotofly_fn_header_content">
        <div class="header_inner">
            <!-- FOR HUGESIZE SCREENS -->
            <div class="header_list">
                <ul class="nav__hor">
                    <li><a class="fotofly_fn_animated_link" href="/Home/Index">Home</a></li>
                    <li>
                        <a class="fotofly_fn_animated_link" href="#">Gallery</a>
                        <ul class="sub_menu">
                            <li>
                                <a class="fotofly_fn_animated_link" href="@Url.Action("Index", "Project", new {page = 1})">
                                    Browse Gallery
                                </a>
                            </li>
                            <li>
                                <a class="fotofly_fn_animated_link" href="@Url.Action("MyProjects","Project")">
                                    My Projects
                                </a>
                            </li>
                            <li>
                                <a class="fotofly_fn_animated_link" href="@Url.Action("Subscribed", "Project")">
                                    My Subscribes
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li><a class="fotofly_fn_animated_link" href="/Home/Portfolio">Portfolio</a></li>
                </ul>
                <div class="logo">
                    <a href="/Home/Index">
                        <img class="light" src="@Url.Content("~/Content/mytemplate/")img/logo.png" alt="" />
                        <img class="dark" src="@Url.Content("~/Content/mytemplate/")img/logo.png" alt="" />
                    </a>
                </div>
                <ul class="nav__hor">
                    <li><a class="fotofly_fn_animated_link" href="/Home/Event">Events</a></li>
                    <li><a class="fotofly_fn_animated_link" href="/Community/Index">Blog</a></li>
                    <li><a class="fotofly_fn_animated_link" href="/Home/Profil">Profil</a></li>
                    <li>
                        <a class="fotofly_fn_animated_link" href="#">Shop</a>
                        <ul class="sub_menu">
                            <li>
                                <a class="fotofly_fn_animated_link" href="@Url.Action("Index", "Shop")">
                                    Shop
                                </a>
                            </li>
                            <li>
                                <a class="fotofly_fn_animated_link" href="@Url.Action("MyItems","Shop")">
                                    My Items
                                </a>
                            </li>
                            <li>
                                <a class="fotofly_fn_animated_link" href="@Url.Action("MyOrders", "Shop")">
                                    My Orders
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /FOR HUGESIZE SCREENS -->
            <!-- EXTRA BUTTONS -->
            <div class="header_helper">
                <ul>
                    <li class="search">
                        <a href="#"><img class="svg" src="@Url.Content("~/Content/mytemplate/")img/svg/search.svg" alt="" /></a>
                        <div class="fotofly_fn_search">
                            <div class="in">
                                <form id="searchForm" action="@Url.Action("SearchByKeyword", "Project")" method="get">
                                    <input type="search" name="keyword" placeholder="Search" />
                                    <a href="#" onclick="sendForm()"><img class="svg" src="@Url.Content("~/Content/mytemplate/")img/svg/search.svg" alt="" /></a>
                                </form>
                            </div>
                        </div>
                    </li>
                    <li class="share">
                        <a href="#"><img class="svg" src="@Url.Content("~/Content/mytemplate/")img/svg/share.svg" alt="" /></a>
                        <ul class="hidden">
                            <li><a href="#"><i class="xcon-facebook-1"></i></a></li>
                            <li><a href="#"><i class="xcon-instagram"></i></a></li>
                            <li><a href="#"><i class="xcon-pinterest-1"></i></a></li>
                            <li><a href="#"><i class="xcon-twitter-1"></i></a></li>
                            <li><a href="#"><i class="xcon-gplus-1"></i></a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>
<script>
    function sendForm() {
        $("#searchForm").submit();
    }
</script>
<!-- /HEADER -->

ArtsukiWeb/Views/Shared/_PageWithoutFooter.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="FotoFly">
    <meta name="author" content="Frenify">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Anonymous+Pro:400,400i,700,700i|Poppins:300,400,500,600,700&amp;subset=cyrillic" rel="stylesheet">
    <!-- STYLES -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/mytemplate/")css/plugins.css" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/mytemplate/")css/style.css" />
    <!--[if lt IE 9]> <script type="text/javascript" src="js/modernizr.custom.js"></script> <![endif]-->
    <!-- /STYLES -->
    <!-- SCRIPTS -->
    <script type="text/javascript" src="@Url.Content("~/Content/mytemplate/")js/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>
    <!--[if lt IE 10]> <script type="text/javascript" src="js/ie8.js"></script> <![endif]-->
    <script type="text/javascript" src="@Url.Content("~/Content/mytemplate/")js/plugins.js"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/mytemplate/")js/init.js"></script>
    <!-- /SCRIPTS -->
</head>
<body style="background-color: #f5f5f5">
    <!-- WRAPPER ALL -->
<div class="fotofly_fn_wrapper_all" data-totop="on">

    @Html.Partial("_Menu")
    <div>
        @RenderBody()
    </div>
</div>
@RenderSection("scripts", required:false)
</body>
</html>

ArtsukiWeb/Views/Shared/_TemplateWithoutPagination.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="description" content="FotoFly">
    <meta name="author" content="Frenify">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Anonymous+Pro:400,400i,700,700i|Poppins:300,400,500,600,700&amp;subset=cyrillic" rel="stylesheet">
    <!-- STYLES -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css"/>
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/mytemplate/")css/plugins.css" />
    <link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/mytemplate/")css/style.css" />
    <style>
        
        .sk-cube-grid {
            width: 40px;
            height: 40px;
            margin: 100px auto;
        }

        .sk-cube-grid .sk-cube {
            width: 33%;
            height: 33%;
            background-color: #333;
            float: left;
            -webkit-animation: sk-cubeGridScaleDelay 1.3s infinite ease-in-out;
            animation: sk-cubeGridScaleDelay 1.3s infinite ease-in-out; 
        }
        .sk-cube-grid .sk-cube1 {
            -webkit-animation-delay: 0.2s;
            animation-delay: 0.2s; }
        .sk-cube-grid .sk-cube2 {
            -webkit-animation-delay: 0.3s;
            animation-delay: 0.3s; }
        .sk-cube-grid .sk-cube3 {
            -webkit-animation-delay: 0.4s;
            animation-delay: 0.4s; }
        .sk-cube-grid .sk-cube4 {
            -webkit-animation-delay: 0.1s;
            animation-delay: 0.1s; }
        .sk-cube-grid .sk-cube5 {
            -webkit-animation-delay: 0.2s;
            animation-delay: 0.2s; }
        .sk-cube-grid .sk-cube6 {
            -webkit-animation-delay: 0.3s;
            animation-delay: 0.3s; }
        .sk-cube-grid .sk-cube7 {
            -webkit-animation-delay: 0s;
            animation-delay: 0s; }
        .sk-cube-grid .sk-cube8 {
            -webkit-animation-delay: 0.1s;
            animation-delay: 0.1s; }
        .sk-cube-grid .sk-cube9 {
            -webkit-animation-delay: 0.2s;
            animation-delay: 0.2s; }

        @@-webkit-keyframes sk-cubeGridScaleDelay {
        0%, 70%, 100% {
            -webkit-transform: scale3D(1, 1, 1);
            transform: scale3D(1, 1, 1);
        } 35% {
              -webkit-transform: scale3D(0, 0, 1);
              transform: scale3D(0, 0, 1); 
          }
        }

        @@keyframes sk-cubeGridScaleDelay {
        0%, 70%, 100% {
            -webkit-transform: scale3D(1, 1, 1);
            transform: scale3D(1, 1, 1);
        } 35% {
              -webkit-transform: scale3D(0, 0, 1);
              transform: scale3D(0, 0, 1);
          } 
        }
    </style>
    <!--[if lt IE 9]> <script type="text/javascript" src="js/modernizr.custom.js"></script> <![endif]-->
    <!-- /STYLES -->
    <!-- SCRIPTS -->
    <script type="text/javascript" src="@Url.Content("~/Content/mytemplate/")js/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>
    <!--[if lt IE 10]> <script type="text/javascript" src="js/ie8.js"></script> <![endif]-->
    <script type="text/javascript" src="@Url.Content("~/Content/mytemplate/")js/plugins.js"></script>
    <script type="text/javascript" src="@Url.Content("~/Content/mytemplate/")js/init.js"></script>
    @RenderSection("HeaderScript", required:false)
    <script type="text/javascript">
        $(window).load(function() {
            $(".loader").fadeOut("slow");
        });
    </script>
    <!-- /SCRIPTS -->
</head>
<body>
    <!-- WRAPPER ALL -->
    <div class="fotofly_fn_wrapper_all" data-totop="on">

    <!-- HEADER -->
    @Html.Partial("_Menu")
    <!-- /HEADER -->
    <div>
        @RenderBody()
    </div>
    <!-- FOOTER -->
    <footer class="fotofly_fn_footer">
        <div class="copyright">
            <span>Copyright 2017. Designed by <a href="#">Frenify</a></span>
        </div>
    </footer>
    <!-- /FOOTER -->
</div>
@RenderSection("scripts", required:false)
<script>
    function trytoredirect(link){
        $('.loader').show();
        settimeout(redirect(link), 6000);
        $('fotofly_fn_masonry mypost').hide();
// show loading in 3 secound before redirect this is example
    }

    function redirect(link) {
        location.href = link;
    }
</script>
</body>
</html>