ArtsukiWeb/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ArtsukiWeb.Models
{
    public class EventViewModel
    {
        public string category { get; set; }

        public string description { get; set; }
        public int nbSeats { get; set; }
        public string photo { get; set; }
        public string places { get; set; }
        public string type { get; set; }
        public int id { get; set; }
        public string title { get; set; }
        public ArtsukiViewModel publisher { get; set; }

        public int etat { get; set; }
        
        public String dateEnd { get; set; }
       
        public String dateStart { get; set; }
        
        public String datePub { get; set; }
    


    }
}

ArtsukiWeb/Models/ExperienceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ArtsukiWeb.Models
{
    public class ExperienceViewModel
    {   public int Id { get; set; }
        public string Photo { get; set; }
        
        public string Comment { get; set; }
        public int Rate { get; set; }
        


    }
}

ArtsukiWeb/Controllers/EventController.cs
using ArtsukiDomain.Entities;
using ArtsukiService;
using ArtsukiServices;
using ArtsukiWeb.Models;
using RestSharp;
using RestSharp.Deserializers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ArtsukiWeb.Controllers
{
    public class EventController : Controller
    {
        private EventService eventService = new EventService();
        private ExperienceService expService = new ExperienceService();

        private const string BASE_URI = "http://localhost:18080/tn.esprit.twin.artsuki-web/api/";
        private const string UPLOAD_PATH = "";
        private ArtsukiViewModel connectedUser;
        private string token;

        public void authenticate()
        {
            var client = new RestClient(BASE_URI);
            var request = new RestRequest(Method.POST);
            client.ClearHandlers();
            client.AddHandler("application/json", new JsonDeserializer());
            request.RequestFormat = DataFormat.Json;
            request.Resource = "authentication/";
            var obj = new
            {
                email = "artsuki7@artsuki.com",
                password = "753357"

            };
            request.AddJsonBody(obj);
            client.AddDefaultHeader("accept", "*/*");
            var response = client.Execute(request);
            token = response.Content;
        }
        [Route("Token")]
        public ActionResult Token()
        {
            authenticate();
            return Content(token);
        }

        public ArtsukiViewModel getConnectedUser()
        {
            if (token == null)
            {
                authenticate();
            }

            if (connectedUser == null)
            {
                var client = new RestClient(BASE_URI);
                client.AddDefaultHeader("accept", "*/*");
                client.AddDefaultHeader("authorization", "Bearer " + token);
                var request = new RestRequest(Method.GET);
                request.Resource = "artsuki";
                var response = client.Execute<ArtsukiViewModel>(request);
                if (response.StatusCode == HttpStatusCode.Unauthorized)
                {
                    authenticate();
                    getConnectedUser();
                }
                connectedUser = response.Data;
                return connectedUser;
            }
            return connectedUser;
        }




        // GET: Event
        public ActionResult Index()
        {
            var events = eventService.GetAll();
            var client = new RestClient(BASE_URI);
            var request = new RestRequest("event/all");
            request.Method = Method.GET;
            Archive();
            request.OnBeforeDeserialization = resp => { resp.ContentType = "application/json"; };
            var response = client.Execute<List<EventViewModel>>(request);
            // ViewBag.ConnectedUser = getConnectedUser();

            return View(response.Data);
        }
        public void Archive()
        {
            var events = new EventViewModel();
            var client = new RestClient(BASE_URI);
            client.AddDefaultHeader("accept", "*/*");
            var request = new RestRequest("event/archive", Method.PUT);
            request.AddJsonBody(events);
            client.Execute(request);


        }


        public ActionResult Details(int id)
        {            
            var clientResult = new RestClient(BASE_URI);
            var request = new RestRequest("event/show", Method.POST);
            clientResult.AddDefaultHeader("accept", "*/*");
            var obj = new EventViewModel() { id = id };
            ViewBag.Connected = getConnectedUser();
            Archive();
            request.AddJsonBody(obj);
            var response = clientResult.Execute<EventViewModel>(request);
            
            
            List<Experience> CommentList = new List<Experience>();
            foreach (var item in expService.getExperienceEvent(id))
            {
                Experience f = new Experience();
                f.Id = item.Id;
                f.Comment = item.Comment;
                CommentList.Add(f);
            }
            ViewBag.Comments = CommentList;
            ViewBag.Rating = expService.AvgEvent(id);

            return View(response.Data);
        }

        // GET: Events/Create
        public ActionResult Create()
        {
            // EventViewModel om = new EventViewModel();
            return View();
        }
        // POST: Events/Create
        [HttpPost]
        public ActionResult Create(HttpPostedFileBase photo)
        {
            try
            {
                var title = Request.Form["title"];
                var description = Request.Form["description"];
                var category = Request.Form["category"];
                var type = Request.Form["type"];
                var place = Request.Form["place"];
                var nbseats = Request.Form["nbSeat"];
                DateTime dateStart = Convert.ToDateTime(Request.Form["dateStart"]).Date;
                DateTime dateEnd = Convert.ToDateTime(Request.Form["dateEnd"]).Date;
                var photoName = Path.GetFileName(photo.FileName);
                string path = Path.Combine(Server.MapPath("~/Content/Upload/Event"),
                Path.GetFileName(photo.FileName));
                photo.SaveAs(path);
                var events = new EventViewModel();
                
                events.category = category;
                events.description = description;
                events.title = title;
                events.places = place;
                events.type = type;
                events.photo = photoName;
                events.nbSeats = Int32.Parse(nbseats);
                events.etat = 1;
                events.dateEnd =  dateEnd.ToString("yyyy-MM-ddTHH:mm:ssZ");
                events.dateStart = dateStart.ToString("yyyy-MM-ddTHH:mm:ssZ");
                //To make sure that the token is valid
                authenticate();

                var restClient = new RestClient(BASE_URI);
                restClient.AddDefaultHeader("accept", "*/*");
                restClient.AddDefaultHeader("authorization", "Bearer " + token);
                var request = new RestRequest("event", Method.POST);
                request.AddJsonBody(events);
                var response = restClient.Execute(request);
                if (response.StatusCode != HttpStatusCode.Created)
                {
                    ViewBag.ErrorMessage = "Description is Too long";
                    return RedirectToAction("Create");
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message = "ERROR:" + ex.Message.ToString();
                return RedirectToAction("Create");
            }

        }
        // GET: Events/Edit/5
        public ActionResult Edit(int id)
        {
            var restClient = new RestClient(BASE_URI);
            var request = new RestRequest("event/show", Method.POST);
            restClient.AddDefaultHeader("accept", "*/*");
            restClient.AddDefaultHeader("authorization", "Bearer " + token);
            var events = new EventViewModel() { id = id };

            request.AddJsonBody(events);
            request.OnBeforeDeserialization = resp => { resp.ContentType = "application/json"; };
            var response = restClient.Execute<EventViewModel>(request);

            return View(response.Data);


        }

        // POST: Events/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, HttpPostedFileBase photo)
        {
            try
            {
                var title = Request.Form["title"];
                var description = Request.Form["description"];
                var category = Request.Form["category"];
                var type = Request.Form["type"];
                var place = Request.Form["place"];
                var photoName = Request.Form["photo"];
                if (photo != null && photo.ContentLength > 0)
                {
                    // TODO: Add insert logic here
                    photoName = Path.GetFileName(photo.FileName);
                    string path = Path.Combine(Server.MapPath("~/Content/Upload/Event"),
                        Path.GetFileName(photo.FileName));
                    photo.SaveAs(path);
                }

                var events = new EventViewModel() { id = id };
                events.category = category;
                events.description = description;
                events.title = title;
                events.places = place;
                events.type = type;
                events.photo = photoName;
                //To make sure that the token is valid
                authenticate();
                var restClient = new RestClient(BASE_URI);
                restClient.AddDefaultHeader("accept", "*/*");
                restClient.AddDefaultHeader("authorization", "Bearer " + token);
                var request = new RestRequest("event", Method.POST);
                request.AddJsonBody(events);
                var response = restClient.Execute(request);
                if (response.StatusCode != HttpStatusCode.Created)
                {
                    ViewBag.ErrorMessage = "Description is Too long";
                    return RedirectToAction("Edit", id);
                }
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Message = "ERROR:" + ex.Message.ToString();
                return RedirectToAction("Edit", id);
            }
        }

        // GET: Events/Delete/5
        public ActionResult Delete(int id)
        {
            var events = new EventViewModel() { id = id, publisher = getConnectedUser() };

ArtsukiWeb/Controllers/ExperienceController.cs
using ArtsukiDomain.Entities;
using ArtsukiService;
using ArtsukiWeb.Models;
using RestSharp;
using RestSharp.Deserializers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ArtsukiWeb.Controllers
{
    public class ExperienceController : Controller
    {
        private ExperienceService expService = new ExperienceService();
        private const string BASE_URI = "http://localhost:18080/tn.esprit.twin.artsuki-web/api/";
        private const string UPLOAD_PATH = "";
        private ArtsukiViewModel connectedUser;
        private string token;
        public void authenticate()
        {
            var client = new RestClient(BASE_URI);
            var request = new RestRequest(Method.POST);
            client.ClearHandlers();
            client.AddHandler("application/json", new JsonDeserializer());
            request.RequestFormat = DataFormat.Json;
            request.Resource = "authentication/";
            var obj = new
            {
                email = "artsuki5@artsuki.com",
                password = "753357"

            };
            request.AddJsonBody(obj);
            client.AddDefaultHeader("accept", "*/*");
            var response = client.Execute(request);
            token = response.Content;
        }
        [Route("Token")]
        public ActionResult Token()
        {
            authenticate();
            return Content(token);
        }

        public ArtsukiViewModel getConnectedUser()
        {
            if (token == null)
            {
                authenticate();
            }

            if (connectedUser == null)
            {
                var client = new RestClient(BASE_URI);
                client.AddDefaultHeader("accept", "*/*");
                client.AddDefaultHeader("authorization", "Bearer " + token);
                var request = new RestRequest(Method.GET);
                request.Resource = "artsuki";
                var response = client.Execute<ArtsukiViewModel>(request);
                if (response.StatusCode == HttpStatusCode.Unauthorized)
                {
                    authenticate();
                    getConnectedUser();
                }
                connectedUser = response.Data;
                return connectedUser;
            }
            return connectedUser;
        }
        // GET: Experience
        public ActionResult Index()
        {
            return View();
        }

        // GET: Experience/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Experience/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Experience/Create
        [HttpPost]
        public ActionResult Create(List<HttpPostedFileBase> photos)
        {
            foreach(var photo in photos) { 
    
            Experience o = new Experience()
            {
              
                Photo = photo.FileName
            };

            expService.Add(o);
            expService.Commit();
}
            return RedirectToAction("Event/Index");
            
           

        
            /*foreach (var file in myFiles)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                    file.SaveAs(Server.MapPath("~/Content/Upload/Event" + file.FileName));

                    Experience exp = new Experience()
                        {
                            Photo = file.FileName,
                            
                        };
                        expService.Add(exp);
                        expService.Commit();
                        
                    }
                }*/
              

            
        }

            // GET: Experience/Edit/5
            public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Experience/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Experience/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Experience/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ArtsukiWeb/Views/Event/Create.cshtml
@model ArtsukiWeb.Models.EventViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Menu.cshtml";
}
<div class="fotofly_fn_content">
    <!-- BREADCRUMBS -->
    <div class="fotofly_fn_breadcrumbs">
        <div class="fotofly_fn_breadcrumbs_content">
            <div class="container">
                <p>
                    <a href="/Home/Index">Home</a>
                    /
                    <a href="Index">Event</a>
                    /
                    <span>New Event</span>
                </p>
            </div>
        </div>
    </div>
    <div class="fotofly_fn_blog_single_wrap">
        <div class="fotofly_fn_blog_single">
            <div class="blog_single">
                <div class="container">
                    <div class="blog_single_wrapper">

                        <div class="fotofly_fn_comment_wrapper">
                            <div class="fotofly_fn_comment">
                                <!-- COMMENTS -->
                                <div class="comments">
                                    <div class="add_comment_wrap">
                                        <div class="add_comment">
                                            <div class="title_holder">
                                                <h3>Create an Event !</h3>
                                            </div>
                                            @using (Html.BeginForm("Create", "Event", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                            {
                                                <div class="your-name">
                                                    <label>Title<span>*</span></label>
                                                    <input type="text" id="creator-name" name="title" placeholder="Event's Title'" />
                                                </div>
                                                <div class="your-email">
                                                    <label>Category<span>*</span></label>
                                                    <select value="" name="category">
                                                        <option value="cinema">Cinema</option>
                                                        <option value="booksigning">Book Signing</option>
                                                    </select>
                                                </div>
                                               
                                                    <label>Starting Date<span>*</span></label>
                                                    <input type="date"  name="dateStart" />
                                                    <label>Ending Date<span>*</span></label>
                                                    <input type="date" name="dateEnd" />
                                                   
                                                    
                                                <div class="your-email">
                                                    <label>Type<span>*</span></label>
                                                    <select value="" name="type" >
                                                        <option value="unlimitedSeats">Unlimited Seats</option>
                                                        <option value="limitedSeats">Limited Seats</option>

                                                    </select>
                                                </div>
                                             
                                                <div class="your-comment ss">
                                                    <label>Number of seats<span>*</span></label>
                                                    <input type="number" id="creator-name" name="nbSeat" placeholder="Seats'" />
                                                </div>
                                                <div class="your-website">
                                                    <label>Photo</label>
                                                    <input required type="file" name="photo" id="creator-website" placeholder="your file .."  />
                                                </div>
                                                <div class="your-comment">
                                                    <label>Place<span>*</span></label>
                                                    <input type="text" id="creator-name" name="place" placeholder="Localisation'" />
                                                </div>
                                                <div class="your-comment">
                                                    <label>Description<span>*</span></label>
                                                    <textarea id="creator-comment" cols="3" name="description" rows="10" placeholder="Description of the Event"></textarea>
                                                </div>


                                                <div class="your-button">
                                                    <input type="submit" id="creator-submit" value="Create your Event" />
                                                </div>
                                                @ViewBag.Message
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ArtsukiWeb/Views/Event/Edit.cshtml
@model ArtsukiWeb.Models.EventViewModel
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Menu.cshtml";
}
<div class="fotofly_fn_content">
    <!-- BREADCRUMBS -->
    <div class="fotofly_fn_breadcrumbs">
        <div class="fotofly_fn_breadcrumbs_content">
            <div class="container">
                <p>
                    <a href="/Home/Index">Home</a>
                    /
                    <a href="Index">Event</a>
                    /
                    <span>New Event</span>
                </p>
            </div>
        </div>
    </div>
    <div class="fotofly_fn_blog_single_wrap">
        <div class="fotofly_fn_blog_single">
            <div class="blog_single">
                <div class="container">
                    <div class="blog_single_wrapper">

                        <div class="fotofly_fn_comment_wrapper">
                            <div class="fotofly_fn_comment">
                                <!-- COMMENTS -->
                                <div class="comments">
                                    <div class="add_comment_wrap">
                                        <div class="add_comment">
                                            <div class="title_holder">
                                                <h3>Create an Event !</h3>
                                            </div>
                                            @using (Html.BeginForm("Edit", "Event", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                            {
                                                <div class="your-name">
                                                    <label>Title<span>*</span></label>
                                                    <input type="text" id="creator-name" name="title" value="@Model.title" placeholder="Event's Title'" />
                                                </div>
                                                <div class="your-email">
                                                    <label>Category<span>*</span></label>
                                                    <select value="@Model.category" name="category">
                                                        <option value="cinema">Cinema</option>
                                                        <option value="booksigning">Book Signing</option>


                                                    </select>
                                                </div>
                                                <div class="your-email">
                                                    <label>Type<span>*</span></label>
                                                    <select value="@Model.type" name="type">
                                                        <option value="unlimitedSeats">Unlimited Seats</option>
                                                        <option value="limitedSeats">Limited Seats</option>

                                                    </select>
                                                </div>
                                                <div class="your-website">
                                                    <label>Photo</label>
                                                    <img src="../../Content/Upload/Event/@Model.photo" alt="" width="100" />
                                                    <input required type="file" name="photo" id="creator-website" placeholder="your file .." />
                                                </div>
                                                <div class="your-comment">
                                                    <label>Place<span>*</span></label>
                                                    <input type="text" id="creator-name" value="@Model.places" name="place" placeholder="Localisation'" />
                                                </div>
                                                <div class="your-comment">
                                                    <label>Description<span>*</span></label>
                                                    <textarea id="creator-comment" cols="3" value="@Model.description" name="description" rows="10" placeholder="Description of the Event"></textarea>
                                                </div>


                                                <div class="your-button">
                                                    <input type="submit" id="creator-submit" value="Create your Event" />
                                                </div>
                                                @ViewBag.Message
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ArtsukiWeb/Views/Event/ExperienceView.cshtml
@using ArtsukiWeb.Models
@using ArtsukiDomain.Entities
@model IEnumerable<ArtsukiWeb.Models.ExperienceViewModel>
@{
    ViewBag.Title = "ExperienceView";
    Layout = "~/Views/Shared/_Details.cshtml";
}

<!-- CONTENT -->
<div class="fotofly_fn_content">
    <div class="fotofly_fn_breadcrumbs">
        <div class="fotofly_fn_breadcrumbs_content">
            <div class="container">

                <p>
                    <a href="/Home/Index">Home</a>
                    /
                    <a href="/Event/Index">Events</a>
                    /
                    <span>Photos</span>
                </p>
            </div>
        </div>
    </div>
    <div class="fotofly_fn_gallery">
        <div class="fotofly_fn_gallery_in">
            <div class="gallery_page">

                <div class="gallery_list gallery">
                    <ul class="fotofly_fn_masonry">
                        @foreach (ExperienceViewModel e in Model) { 
                        <li class="fotofly_fn_masonry_in">
                            <div class="item">
                                <img src="../../Content/Upload/Event/@e.Photo" alt="nope" />
                            </div>
                        </li>
                        }
                    </ul>
                </div>


            </div>
        </div>
    </div>


</div>
<!-- /CONTENT -->

ArtsukiWeb/Views/Event/Index.cshtml
@using ArtsukiWeb.Models
@using ArtsukiDomain.Entities
@model IEnumerable<ArtsukiWeb.Models.EventViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Details.cshtml";

}
<!-- CONTENT -->
<div class="fotofly_fn_content">

    <!-- CLIENTS -->
    <div class="fotofly_fn_clients">
        <div class="fotofly_fn_clients_in">
            <div class="container">
                <div class="clients_wrap">

                    <!-- BREADCRUMBS -->
                    <div class="fotofly_fn_breadcrumbs">
                        <div class="fotofly_fn_breadcrumbs_content">
                            <div class="container">

                                <p>
                                    <a href="/Home/Index">Home</a>
                                    /
                                    <span>Events</span>
                                </p>
                            </div>
                        </div>
                    </div>
                    <!-- /BREADCRUMBS -->
                    <a href="@Url.Action("Create","Event")">Add Event</a>

                    <div class="title_holder">
                        <h3>Our Events</h3>
                    </div>


                    <div class="clients_list">
                        <ul class="fotofly_fn_masonry">


                            @foreach (EventViewModel e in Model)
                            {
                               // var dt = new DateTime(1970, 1, 1, 0, 0, 0, 0).AddSeconds(Math.Round(e.datePub / 1000d)).ToString("yyyy/MM/dd");
 
                                <li class="fotofly_fn_masonry_in">
                                    <div class="item">
                                        <div class="img_holder">
                                            <a href="@Url.Action("Details", new {id = e.id})"><img src="../../Content/Upload/Event/@e.photo" alt="" /></a>
                                        </div>
                                        <div class="name_holder">
                                            <span>@e.description </span>
                                            <a href="/Event/Details">@e.title </a>
                                        </div>
                                    </div>
                                </li>

                            }

                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <!-- /CLIENTS -->

</div>
<!-- /CONTENT -->