ArtsukiWeb/Models/ExperienceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ArtsukiWeb.Models
{
    public class ExperienceViewModel
    {   public int Id { get; set; }
        public string Photo { get; set; }
        
        public string Comment { get; set; }
        public int Rate { get; set; }
        


    }
}

ArtsukiWeb/Controllers/ExperienceController.cs
using ArtsukiDomain.Entities;
using ArtsukiService;
using ArtsukiWeb.Models;
using RestSharp;
using RestSharp.Deserializers;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace ArtsukiWeb.Controllers
{
    public class ExperienceController : Controller
    {
        private ExperienceService expService = new ExperienceService();
        private const string BASE_URI = "http://localhost:18080/tn.esprit.twin.artsuki-web/api/";
        private const string UPLOAD_PATH = "";
        private ArtsukiViewModel connectedUser;
        private string token;
        public void authenticate()
        {
            var client = new RestClient(BASE_URI);
            var request = new RestRequest(Method.POST);
            client.ClearHandlers();
            client.AddHandler("application/json", new JsonDeserializer());
            request.RequestFormat = DataFormat.Json;
            request.Resource = "authentication/";
            var obj = new
            {
                email = "artsuki5@artsuki.com",
                password = "753357"

            };
            request.AddJsonBody(obj);
            client.AddDefaultHeader("accept", "*/*");
            var response = client.Execute(request);
            token = response.Content;
        }
        [Route("Token")]
        public ActionResult Token()
        {
            authenticate();
            return Content(token);
        }

        public ArtsukiViewModel getConnectedUser()
        {
            if (token == null)
            {
                authenticate();
            }

            if (connectedUser == null)
            {
                var client = new RestClient(BASE_URI);
                client.AddDefaultHeader("accept", "*/*");
                client.AddDefaultHeader("authorization", "Bearer " + token);
                var request = new RestRequest(Method.GET);
                request.Resource = "artsuki";
                var response = client.Execute<ArtsukiViewModel>(request);
                if (response.StatusCode == HttpStatusCode.Unauthorized)
                {
                    authenticate();
                    getConnectedUser();
                }
                connectedUser = response.Data;
                return connectedUser;
            }
            return connectedUser;
        }
        // GET: Experience
        public ActionResult Index()
        {
            return View();
        }

        // GET: Experience/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Experience/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Experience/Create
        [HttpPost]
        public ActionResult Create(List<HttpPostedFileBase> photos)
        {
            foreach(var photo in photos) { 
    
            Experience o = new Experience()
            {
              
                Photo = photo.FileName
            };

            expService.Add(o);
            expService.Commit();
}
            return RedirectToAction("Event/Index");
            
           

        
            /*foreach (var file in myFiles)
                {
                    if (file != null && file.ContentLength > 0)
                    {
                    file.SaveAs(Server.MapPath("~/Content/Upload/Event" + file.FileName));

                    Experience exp = new Experience()
                        {
                            Photo = file.FileName,
                            
                        };
                        expService.Add(exp);
                        expService.Commit();
                        
                    }
                }*/
              

            
        }

            // GET: Experience/Edit/5
            public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Experience/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Experience/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Experience/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ArtsukiWeb/Views/Experience/Create.cshtml
@model 
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Details.cshtml";
}

<!-- CONTENT -->
<div class="fotofly_fn_content">

    <div class="fotofly_fn_gallery">
        <div class="fotofly_fn_gallery_in">
            <div class="gallery_page">

                <div class="gallery_list gallery">
                    <ul class="fotofly_fn_masonry">
                        <li class="fotofly_fn_masonry_in">
                            <div class="item">
                                <a href="@Url.Content("~/Content/mytemplate/")img/blog/post_1.jpg"><img src="@Url.Content("~/Content/mytemplate/")img/blog/post_1.jpg" alt="" /></a>
                            </div>
                        </li>
                       
                    </ul>
                </div>


            </div>
        </div>
    </div>


</div>
<!-- /CONTENT -->

ArtsukiWeb/Views/Experience/Upload.cshtml
@model ArtsukiWeb.Models.ExperienceViewModel
@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_Menu.cshtml";
}
<div class="fotofly_fn_content">
    <!-- BREADCRUMBS -->
    <div class="fotofly_fn_breadcrumbs">
        <div class="fotofly_fn_breadcrumbs_content">
            <div class="container">
                <p>
                    <a href="/Home/Index">Home</a>
                    /
                    <a href="Index">Event</a>
                    /
                    <span>New Event</span>
                </p>
            </div>
        </div>
    </div>
    <div class="fotofly_fn_blog_single_wrap">
        <div class="fotofly_fn_blog_single">
            <div class="blog_single">
                <div class="container">
                    <div class="blog_single_wrapper">

                        <div class="fotofly_fn_comment_wrapper">
                            <div class="fotofly_fn_comment">
                                <!-- COMMENTS -->
                                <div class="comments">
                                    <div class="add_comment_wrap">
                                        <div class="add_comment">
                                            <div class="title_holder">
                                                <h3>Create an Event !</h3>
                                            </div>
                                            @using (Html.BeginForm("Upload", "Experience", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                            {



                                                <div class="your-website">
                                                    <label>Photo</label>
                                                    <input required type="file" name="photo" id="creator-website" placeholder="your file .." multiple />
                                                </div>



                                                <div class="your-button">
                                                    <input type="submit" id="creator-submit" value="Create your Event" />
                                                </div>
                                                @ViewBag.Message
                                            }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>